[project]
name = "exam"
version = "0.1.0"
description = "transport bot"
authors = [
    {name = "ephoriab5",email = "nagibruslan@gmail.com"}
]
requires-python = ">=3.12,<4.0.0"
dependencies = [
    "google-adk (>=2.1.0,<3.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
