[project]
name = "7lab"
package-mode = false
version = "0.1.0"
description = ""
authors = [
    {name = "ephoriab5",email = "nagibruslan@gmail.com"}
]
requires-python = ">=3.13,<4.0"
dependencies = [
    "google-adk (>=1.32.0,<2.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
